" メニューバーを非表示にする。
set guioptions-=T

" フォントを設定する。
set guifont=ＭＳ_ゴシック:h9

" 選択範囲をシステムのクリップボードにコピーする。
if has('win32')
  set guioptions+=a
endif

" スワップ・ファイルは $TEMP に作る。
if has('win32')
  set directory=$TEMP
endif
