" メニューバーを非表示にする。
set guioptions-=T

" フォント、サイズを設定する。
let g:gui_font_name="ＭＳ_ゴシック"
if dotfiles#test_font_availability("Cica")
  let g:gui_font_name="Cica"
endif

command! MyFontSize09 call dotfiles#set_gui_font(9)
command! MyFontSize14 call dotfiles#set_gui_font(14)
command! MyFontSize18 call dotfiles#set_gui_font(18)
command! MyFontSize22 call dotfiles#set_gui_font(22)
MyFontSize18

" 選択範囲をシステムのクリップボードにコピーする。
if has('win32')
  set guioptions+=a
endif

" スワップ・ファイルは $TEMP に作る。
if has('win32')
  set directory=$TEMP
endif
